# Generated by Django 4.2.6 on 2023-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
