# Generated by Django 4.2.6 on 2023-10-29 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 2, 41, 827390)),
        ),
    ]
